create database churndataset;

use churndataset;

#1. What is the total number of customers in the dataset?
select count(*) from churndata;

#2.How many customers have churned versus retained?
select churn, count(*) as Customer_Count from churndata group by churn;

#3.What is the distribution of customers by gender?
Select gender,count(*) as Total from churndata group by gender;

#4.How many customers are senior citizens?
select count(*) from churndata where SeniorCitizen=1;

#5.How many customers have partners or dependents?
select * from churndata where Partner='Yes' or Dependents='Yes';

#6.What is the gender breakdown among churned customers?
select gender, Count(*)as Churned_Customer
from churndata where churn='Yes' group by gender;

#7.Which add-ons (e.g., online security, tech support) are most commonly used by churned customers?
select 'OnlineSecurity' as Category ,OnlineSecurity, count(*) from churndata 
where churn='Yes' group by OnlineSecurity
union all
select 'TechSupport' as Category ,TechSupport, count(*) from churndata 
where churn='Yes' group by TechSupport;

#8. How many customers churned in each tenure range (e.g., 0-12 months, 13-24 months)?
select Case
when tenure<=12 then '0-12 months'
when tenure<=24 then '13-24 months'
when tenure<=36 then '25-36 months'
else '37+ months'
end as Tenure_Range, count(*) as Churned_Customers from churndata
where churn='Yes' group by Tenure_Range;

#9. What is the churn rate based on contract type (Month-to-month, One year, Two year)?
select Contract,(Count(*) / (select count(*) from churndata where Contract is not null))*100
from churndata where churn='Yes' group by Contract;

#10 What is the total revenue from churned customers?
select format(sum(TotalCharges),2) from churndata where churn='Yes';

#11. What is the churn rate by payment method (e.g., electronic check, mailed check)?
select PaymentMethod, (Count(*)/ (select Count(*) from churndata where PaymentMethod is not null))*100
from churndata where churn='Yes' group by  PaymentMethod;

#12. What is the average number of technical tickets raised by churned versus retained customers?
select Churn, avg(numTechTickets) from churndata group by Churn;

#13. What is the average tenure of customers who subscribe to online security but churned?
select avg(Tenure) as Average_Tenure from churndata 
where churn='Yes' and OnlineSecurity='Yes';

#14. What is the total revenue generated by customers on each contract type?
select Contract, format(sum(TotalCharges),2) as Revenue from churndata group by Contract;

#15. How many customers churned within the first 6 months of their tenure?
select count(*) from churndata where Tenure<=6 and Churn='Yes';

#16. Which combination of services has the highest churn rate?
select PhoneService,InternetService,StreamingTV,count(*)/(select count(*) from churndata where Churn='Yes')*100 as Churn_rate
 from churndata where Churn='Yes' group by PhoneService,InternetService,StreamingTV
 order by Churn_rate desc;
 
 #17. Which payment method is most popular among senior citizens who churned?
 Select PaymentMethod,Count(*) as Count from churndata where SeniorCitizen=1 and Churn='Yes'
 group by PaymentMethod order by Count Desc;